SET search_path = db2,pg_catalog,public;

-- VALUE()
SELECT VALUE(1) FROM SYSIBM.SYSDUMMY1; -- DB2 ERROR
SELECT VALUE(NULL) FROM SYSIBM.SYSDUMMY1; -- DB2 ERROR
SELECT VALUE(NULL, NULL) FROM SYSIBM.SYSDUMMY1; -- DB2 ERROR
SELECT VALUE(NULL, 1, NULL) FROM SYSIBM.SYSDUMMY1; -- DB2 ERROR
SELECT VALUE(NULL, '1', NULL) FROM SYSIBM.SYSDUMMY1; -- DB2 ERROR

-- ^= operator
SELECT 1 FROM SYSIBM.SYSDUMMY1 WHERE 1 ^= 2;
SELECT 1 FROM SYSIBM.SYSDUMMY1 WHERE 1 ^= 1;

-- !! operator
SELECT 'FOO' !! ' BAR' FROM SYSIBM.SYSDUMMY1;
